version: '3'
services:
  ui-ft:
    container_name: flight_tracker_ui
    restart: always
    env_file: .env
    build: .
    ports:
      - "5005:5005"
    volumes:
      - ./apps:/apps
  mongo:
    image: mongo:4.4
    command: --nojournal
    volumes:
      - ./db:/data/db/
  orion:
    image: fiware/orion
    links:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo -corsOrigin __ALL -corsMaxAge 600
    depends_on:
      - mongo
  draco:
    image: ging/fiware-draco
    ports:
      - "8080:8080"
      - "5050:5050"
      - "9090:9090"
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=pass1234567890
      - NIFI_WEB_HTTP_PORT=8080
    depends_on:
      - orion
  mysql:
    image: mysql:5.7.22
    restart: always
    command: --default-authentication-plugin=mysql_native_password --ssl=0
    environment:
      - MYSQL_DATABASE=draco-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=6L?op69RSYhT6a7ni?P6
      - MYSQL_ROOT_PASSWORD=6L?op69RSYhT6a7ni?P6
      - MYSQL_ROOT_HOST=%
    ports:
      - '3306:3306'
    volumes:
      - ./draco-db:/var/lib/mysql
