version: '3'
services:
  ui-ft:
    container_name: flight_tracker_ui
    restart: always
    env_file: .env
    build: .
    ports:
      - "5005:5005"
    volumes:
      - ./apps:/apps
  mongo:
    image: mongo:4.4
    command: --nojournal
    volumes:
      - ./db:/data/db/
  orion:
    image: fiware/orion
    links:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo -corsOrigin __ALL -corsMaxAge 600
    depends_on:
      - mongo
  draco:
    image: ging/fiware-draco
    ports:
      - "8080:8080"
      - "5050:5050"
      - "9090:9090"
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=pass1234567890
      - NIFI_WEB_HTTP_PORT=8080
    depends_on:
      - orion
  mysql:
    image: mysql:5.7.22
    restart: always
    command: --default-authentication-plugin=mysql_native_password --ssl=0
    environment:
      - MYSQL_DATABASE=draco-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=6L?op69RSYhT6a7ni?P6
      - MYSQL_ROOT_PASSWORD=6L?op69RSYhT6a7ni?P6
      - MYSQL_ROOT_HOST=%
    ports:
      - '3306:3306'
    volumes:
      - ./draco-db:/var/lib/mysql
  worker:
    container_name: FlightTrackerWorker
    build: .
    command: celery -A apps.celery.worker.celery worker --loglevel=info
    volumes:
      - ./apps:/apps
    env_file:
      - .env
    depends_on:
      - redis
      - ui-ft
  scheduler:
    container_name: FlightTrackerScheduler
    build: .
    command: celery -A apps.celery.worker.celery beat --schedule=/tmp/celerybeat-schedule --loglevel=INFO
    volumes:
      - ./apps:/apps
    env_file:
      - .env
    depends_on:
      - redis
      - ui-ft
  redis:
    container_name: FlightTrackerRedis
    image: redis:6-alpine
    depends_on:
      - ui-ft
  dashboard:
    container_name: FlightTrackerDashboard
    build: .
    command: celery -A apps.celery.worker.celery flower --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5556:5555
    env_file:
      - .env
    depends_on:
      - worker
      - redis
      - ui-ft
